### ISSUE TITLE
Order of subjects

### ISSUE THREAD

**Issue by pijozyb** [vikasverma240896/Ravindrababu-GATE-Lectures-Downloader#2]
Is it possible to change the order of subjects in which the videos are downloaded?
Please explain the procedure

**Comment by vikasverma240896** [comment]
Yes, you can. Before you run the script, open the file.
You'll find the list of subjects. Make changes in the order they're written. It'll do the needed.

**Comment by pooja987654** [comment]
Following error is coming-
Traceback (most recent call last):
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Hp\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Hp\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Hp/Python/Python36-32/script.py", line 71, in <module>
    browser = webdriver.Chrome()
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by vikasverma240896** [comment]
The error itself has the solution to your problem.
Kindly follow the link in the error, download the chrome driver and place it in the needed python directory.
That should solve the problem.
