### ISSUE TITLE
Plz check!! Following error is coming

### ISSUE THREAD

**Issue by pooja987654** [vikasverma240896/Ravindrababu-GATE-Lectures-Downloader#3]
Traceback (most recent call last):
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Hp\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Hp\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Hp/Python/Python36-32/script.py", line 71, in <module>
    browser = webdriver.Chrome()
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\Hp\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by vikasverma240896** [comment]
The error itself has the solution to your problem.
Kindly follow the link in the error, download the chrome driver and place it in the needed python directory.
That should solve the problem.

**Comment by siditrix17** [comment]
after downloading chromedriver from website install it and a cmd pops up with : Starting ChromeDriver 2.15.322448 then go to specific python path in cmd and execute chromedriver.exe if it starts running, you are good to go.

**Comment by pooja987654** [comment]
I m running 2.35.528161.
